name: KiddycraftFarmpig
main: de.kiddycraft.farmpig.FarmPigPlugin
version: 69 -  Lol, that was just a joke. But let's be honest: don't you think it's funny that Spigot allows you to write almost anything as the version of a plugin? I mean, you can write a whole novel into it. Speaking of novels, what do you think of Half Broke Horses? You know, Jeannette Walls' book about her grandmother Lilly's life in the Wild West. So this book fascinated me more than this so-called minecraft. Minecraft is totally overrated anyway. Let's be honest, only small children and losers play it. Wow, look at that, I placed a block. That's soooo exciting. Wow, look here, I smashed a block. Speaking of smashing. Have you played the new Super Smash Bros Ultimate yet? That's absolutely awesome! Much better than this Minecraft. I would immediately trade my Owner Rank for it.
description: For all glorious kiddies that lack so much creativity that they even copy your pork farm.
author: Kevin
depend:

commands:
  farmpig:
    description: Selectively enable nag feature. Use /nagmod to get list of modules.
    usage: |
      /farmpig list - lists all active farmpigs and allows managing.
      /farmpig add <type> [name] - creates a new farmpig at the current position with an optional name.
    permission: kiddycraft.farmpig

permissions:
  kiddycraft.farmpig:
    description: Grants all permissions to ops
